### ISSUE TITLE
Bug Report: vfat_info_uhal.py throws exception with fixed uhal address tables in GEM_AMC 3.8.4

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/cmsgemos#292] opened 2019-06-27 10:02 UTC
## Brief summary of issue

Info tools throw `uhal` exception with fixed address tables.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

No `uhal` exception should be raised.

## Current Behavior

Calling `vfat_info_uhal.py` throws a `uhal` exception:

```bash
% vfat_info_uhal.py -s 2 -g8 --shelf=1
Traceback (most recent call last):
  File "$VIRTUAL_ENV/lib/python2.7/site-packages/gempython/scripts/vfat_info_uhal.py", line 32, in <module>
    amc     = getAMCObject(options.slot,options.shelf,options.debug)
  File "$VIRTUAL_ENV/lib/python2.7/site-packages/gempython/tools/amc_user_functions_uhal.py", line 21, in getAMCObject
    amc             = manager.getDevice( "gem.shelf%02d.amc%02d"%(shelf,slot) )
uhal._core.exception: Exactly one address table file must be specified. The expression "${GEM_ADDRESS_TABLE_PATH}/uhal_gem_amc_ctp7_amc.xml" refers to 0 valid files.
```

But this file is valid:

```bash
(py2.7)% ll ${GEM_ADDRESS_TABLE_PATH}/uhal_gem_amc_ctp7_amc.xml
lrwxr-xr-x. 1 username zh 125 Jun 27 11:16 $BUILD_HOME/addrTables/gem904daq01/uhal_gem_amc_ctp7_amc.xml -> /data/bigdisk/GEMDAQ_Documentation/system/firmware/files/CTP7/v3.8.4/address_table_v3_8_4_GE11_12oh/uhal_gem_amc_ctp7_amc.xml
```

### Steps to Reproduce (for bugs)

1. Call `vfat_info_uhal.py` when using GEM_AMC 3.8.4 address tables.

## Context

Can't use the uhal tools as intended.

## Your Environment

* Version used: `generic-amc-RPC-v3-short-term`
* Shell used: `/bin/zsh`

**Comment by jsturdy** [comment] 2019-06-27 10:09
I doubt the table is valid... (especially since the parser is failing)
Have to check that the bugs reported in the address table generation in evka85/GEM_AMC#27 and evka85/GEM_AMC#34 have been fully addressed...

**Comment by jsturdy** [comment] 2019-06-27 10:10
Indeed, this is still broken:
```xml
      <node id="RAM" address="0x10000" >
        <node id="GBT" address="0x0" permission="rw" mode="block"size="3312"/>
        <node id="VFAT" address="0x10000" permission="rw" mode="block"size="21312"/>
```

**Comment by bdorney** [comment] 2019-06-27 10:15
@evka85 do you think we could hotfix the address tables today?

**Comment by jsturdy** [comment] 2019-06-27 12:31
Not a bug, closing, to be addressed in appropriate repository with a fixed release

**Closed as completed by jsturdy** 2019-06-27 12:31 UTC
Labels: Priority: High
